services:
  identity-service:
    build: .
    image: digitalmaith/identity-service:latest
    ports:
      - "8081:8080"
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1